# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestLog():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_log(self):
        self.driver.get("https://nxbkimdong.com.vn/")
        self.driver.set_window_size(974, 969)
        wait = WebDriverWait(self.driver, 30)  # Chờ tối đa 30 giây

        # Click "Đăng nhập"
        wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Đăng nhập"))).click()
        time.sleep(1)  # Chờ 1 giây sau khi nhấn nút "Đăng nhập"

        # Nhập email
        email_field = wait.until(EC.presence_of_element_located((By.ID, "CustomerEmail")))
        for char in "1231231@gmail.com":
            email_field.send_keys(char)
            time.sleep(0.1)  # Chờ 0.1 giây giữa mỗi ký tự
        time.sleep(1)  # Chờ 1 giây sau khi nhập email

        # Nhập mật khẩu
        password_field = wait.until(EC.presence_of_element_located((By.ID, "CustomerPassword")))
        for char in "123123asd":
            password_field.send_keys(char)
            time.sleep(0.1)  # Chờ 0.1 giây giữa mỗi ký tự
        time.sleep(1)  # Chờ 1 giây sau khi nhập mật khẩu

        # Nhấn nút đăng nhập
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "p:nth-child(7) > .btn"))).click()
        time.sleep(2)  # Chờ 2 giây để hệ thống xử lý đăng nhập

        # Click vào logo
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".text-center > a > img"))).click()
        time.sleep(1)  # Chờ 1 giây sau khi click logo

        # Chọn sản phẩm
        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#home-pro-products-5 h2"))).click()
        time.sleep(2)  # Chờ 2 giây sau khi chọn sản phẩm
