# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys

class TestAzten():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.implicitly_wait(10)  # Thêm thời gian chờ ngầm định
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_azten(self):
        self.driver.get("https://nxbkimdong.com.vn/")
        self.driver.set_window_size(974, 969)

        # Nhấn vào nút menu
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".btnMenu"))
        )
        self.driver.find_element(By.CSS_SELECTOR, ".btnMenu").click()
        time.sleep(1)  # Chờ 1 giây để menu hiển thị

        # Chọn mục thứ 5
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "li:nth-child(5) span"))
        )
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) span").click()
        time.sleep(1)  # Chờ 1 giây để danh mục được tải

        # Nhấp vào dropdown "SortBy"
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.ID, "SortBy"))
        )
        self.driver.find_element(By.ID, "SortBy").click()
        time.sleep(1)  # Chờ 1 giây để dropdown hiển thị

        # Chọn "Tên A-Z"
        dropdown = self.driver.find_element(By.ID, "SortBy")
        dropdown.find_element(By.XPATH, "//option[. = 'Tên A-Z']").click()
        time.sleep(1)  # Chờ 1 giây để lọc danh sách

        # Nhấp vào tùy chọn thứ 3
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "li:nth-child(3) > label > span"))
        )
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > label > span").click()
        time.sleep(1)  # Chờ 1 giây để đảm bảo thao tác được thực hiện
