# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestDangky():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_dangky(self):
        self.driver.get("https://nxbkimdong.com.vn/")
        self.driver.set_window_size(974, 969)
        wait = WebDriverWait(self.driver, 30)  # Chờ tối đa 30 giây

        # Click vào biểu tượng "Đăng ký"
        wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".fa-pencil-square-o"))).click()
        time.sleep(1)  # Chờ 1 giây

        # Click vào "Tạo tài khoản"
        wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Tạo tài khoản"))).click()
        time.sleep(1)  # Chờ 1 giây

        # Nhập tên
        first_name_field = wait.until(EC.presence_of_element_located((By.ID, "FirstName")))
        first_name_field.click()
        first_name_field.send_keys("Nguyen van A")
        time.sleep(1)

        # Nhập số điện thoại
        phone_field = wait.until(EC.presence_of_element_located((By.ID, "Phone")))
        phone_field.click()
        phone_field.send_keys("0932123321")
        time.sleep(1)

        # Nhập email
        email_field = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#create_customer > #Email")))
        email_field.click()
        email_field.send_keys("123321@gmail.com")
        time.sleep(1)

        # Nhập mật khẩu
        password_field = wait.until(EC.presence_of_element_located((By.ID, "CreatePassword")))
        password_field.click()
        password_field.send_keys("123123asd")
        time.sleep(1)

        # Chọn giới tính
        gender_field = wait.until(EC.element_to_be_clickable((By.ID, "CustomerFormMale1")))
        gender_field.click()
        time.sleep(1)

        # Nhập ngày sinh
        birthday_field = wait.until(EC.presence_of_element_located((By.NAME, "customer[birthday]")))
        birthday_field.click()
        birthday_field.clear()
        birthday_field.send_keys("2003-12-11")
        time.sleep(1)

        # Đồng ý nhận email marketing
        marketing_checkbox = wait.until(EC.element_to_be_clickable((By.NAME, "customer[accepts_marketing]")))
        marketing_checkbox.click()
        time.sleep(1)

        # Click "Đăng ký"
        register_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "p:nth-child(14) > .btn")))
        register_button.click()
        time.sleep(2)

        # Click vào logo để quay về trang chủ
        home_logo = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".large--four-twelfths > .hd-logo img")))
        home_logo.click()
        time.sleep(1)
